# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 821, 611))
        self.textBrowser.setStyleSheet("border-image: url(:/img/imgs/1.png);\n"
"border-radius:30px;")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 100, 321, 91))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 210, 251, 51))
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border:lpx solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(0,0,0,100);\n"
"color:rgb(255,255,255);")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 300, 251, 51))
        self.lineEdit_2.setMouseTracking(True)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border:lpx solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(0,0,0,100);\n"
"color:rgb(255,255,255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 131, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("shangdian.png"))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 30, 51, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"image: url(:/img/imgs/关闭.png);\n"
"backgroud-color:rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"padding-bottom:3px;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 480, 161, 51))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setTabletTracking(False)
        self.pushButton_3.setAcceptDrops(False)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"backgroud-color:rgb(0,0,0,0);\n"
"border:2px solid rgba(5,170,129,20);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QpushButton:hover{\n"
"    padding-buttom:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 390, 251, 51))
        self.lineEdit_3.setMouseTracking(True)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border:lpx solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(0,0,0,100);\n"
"color:rgb(255,255,255);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 480, 161, 51))
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setTabletTracking(False)
        self.pushButton_4.setAcceptDrops(False)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"color:rgb(255,255,255);\n"
"backgroud-color:rgb(0,0,0,0);\n"
"border:2px solid rgba(5,170,129,20);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QpushButton:hover{\n"
"    padding-buttom:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffff00;\">Linux系统监控-注册界面</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "账号："))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "密码："))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">登录</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "注册"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">登录</span></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "返回"))
import UI.login.rec_rc
